# Generated by Django 4.2.7 on 2023-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_toilet'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='toilet',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
