# Generated by Django 4.2.7 on 2023-11-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_toilet_latitude_toilet_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
